[package]
name = "arwallet_miner"
version = "0.1.0"
authors = ["littledivy <dj.srivastava23@gmail.com>"]
edition = "2018"

[dependencies]
openssl = { version = "0.10" }
base64 = "0.13.0"
threadpool = "1.8.1"
sha2 = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
