name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: release / ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-pc-windows-msvc
            os: windows-2019
          - target: x86_64-apple-darwin
            os: macos-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - name: Setup Rust (${{ github.event.inputs.toolchain }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Install OpenSSL using brew (macOS)
        if: runner.os == 'macOS'
        run: brew install openssl

      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install openssl --no-progress
          echo "OPENSSL_DIR=C:\Program Files\OpenSSL-Win64" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --target ${{ matrix.target }} --release

      - name: Zip unix build
        if: runner.os != 'Windows'
        working-directory: target/${{ matrix.target }}/release
        run: zip -r arwallet-miner-${{ matrix.target }}.zip arwallet_miner

      - name: Zip windows build
        if: runner.os == 'Windows'
        working-directory: target/${{ matrix.target }}/release
        run: Compress-Archive -Path arwallet_miner.exe -DestinationPath arwallet-miner-${{ matrix.target }}.zip

      - name: Setup Deno
        if: startsWith(matrix.os, 'ubuntu')
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Generate Release Notes
        if: startsWith(matrix.os, 'ubuntu')
        run: deno run -A https://deno.land/x/ghlog/ghlog.ts littledivy/arwallet-miner

      - name: Upload Release Notes
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: notes
          path: CHANGELOG.md
          if-no-files-found: error

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            arwallet-miner-x86_64-unknown-linux-gnu.zip
            arwallet-miner-x86_64-pc-windows-msvc.zip
            arwallet-miner-x86_64-apple-darwin.zip

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.tag }}
          draft: true
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "release/*"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
